name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: notedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: deadpaste
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      ConnectionStrings__Default: Host=localhost;Port=5432;Database=notedb;Username=postgres;Password=deadpaste

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker image (optional)
        run: docker build -t noted-api -f Noted.Api/Dockerfile .

      - name: Run container for health check
        run: |
          docker run -d -p 8080:8080 --name noted-health-test \
            -e ASPNETCORE_URLS=http://+:8080 \
            -e ConnectionStrings__Default="Host=localhost;Port=5432;Database=notedb;Username=postgres;Password=deadpaste" \
            noted-api

          # wait for container to boot
          sleep 5

      - name: Hit /health endpoint
        run: |
          curl --fail http://localhost:8080/health
