name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: notedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: deadpaste
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      ConnectionStrings__Default: Host=localhost;Port=5432;Database=notedb;Username=postgres;Password=deadpaste

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set image tag
        id: vars
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t noted-api -f Noted.Api/Dockerfile .
      
      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag image
        run: docker tag noted-api ${{ secrets.ACR_LOGIN_SERVER }}/noted-api:${{ steps.vars.outputs.TAG }}

      - name: Push image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/noted-api:${{ steps.vars.outputs.TAG }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name noted-api \
            --resource-group NotedRg \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/noted-api:${{ steps.vars.outputs.TAG }}
